[package]
name = "async-oauth2"
authors = [
  "Alex Crichton <alex@alexcrichton.com>",
  "Florin Lipan <florinlipan@gmail.com>",
  "David A. Ramos <ramos@cs.stanford.edu>",
  "John-John Tedro <udoprog@tedro.se>"
]
version = "0.1.0-alpha.2"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/udoprog/async-oauth2"
edition = "2018"

[lib]
name = "oauth2"

[dependencies]
base64 = "0.10.0"
rand = "0.6.5"
serde = {version = "1.0.89", features = ["derive"]}
serde_json = "1.0.39"
sha2 = "0.8.0"
url = "2.1"
reqwest = { version = "=0.10.0-alpha.2", git = "https://github.com/seanmonstar/reqwest" }