[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Florin Lipan <florinlipan@gmail.com>", "David A. Ramos <ramos@cs.stanford.edu>"]
version = "2.0.0-alpha.5"
license = "MIT/Apache-2.0"
description = "Bindings for exchanging OAuth 2 tokens"
repository = "https://github.com/ramosbugs/oauth2-rs"
edition = "2018"

[dependencies]
base64 = "0.10.0"
rand = "0.6.5"
serde = {version = "1.0.89", features = ["derive"]}
serde_json = "1.0.39"
sha2 = "0.8.0"
url = "2.1"
reqwest = { version = "0.10.0-alpha.0", git = "https://github.com/seanmonstar/reqwest.git", rev = "ebe57e10" }

[dev-dependencies]
tokio = { version = "0.2.0-alpha.5" }