[package]
name = "async-oauth2-examples"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[lib]
name = "oauth2_examples"

[dependencies]
reqwest = "=0.10.0-alpha.1"
tokio = "=0.2.0-alpha.6"
hyper = "=0.13.0-alpha.4"
serde = {version = "1.0.101", features = ["derive"]}
serde_urlencoded = "0.6.1"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
tower-service = "=0.3.0-alpha.2"
log = "0.4.8"
failure = "0.1.5"
clap = "2.33.0"
async-oauth2 = {path = ".."}