[package]
name = "async-oauth2-examples"
version = "0.0.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"

[lib]
name = "oauth2_examples"

[dependencies]
reqwest = "0.10.0"
tokio = { version = "0.2.6", features = ["full"] }
hyper = "0.13.1"
serde = {version = "1.0.101", features = ["derive"]}
serde_urlencoded = "0.6.1"
futures = "0.3.0"
tower-service = "0.3.0"
log = "0.4.8"
anyhow = "1.0.26"
clap = "2.33.0"
async-oauth2 = {path = ".."}